[project]
name = "jupyterlab-env"
version = "0.1.0"
description = "wordslab-notebooks jupyterlab environment"
requires-python = ">=3.12,<3.13"
dependencies = [
    "jupyterlab==4.5.1",
    "ipywidgets==8.1.8",
    "ipympl==0.9.8",
    "jupyterlab-execute-time==3.3.0",
    "jupyterlab-git==0.51.3",
    "jupyterlab-nvdashboard==0.13.0",
    "pynvml==12.0.0",
    "jupyter-ai==2.31.7",
    "langchain-ollama==0.3.10",
    "langchain-openai==0.3.35",
    "wordslab-notebooks-lib"
]
